# Generated by Django 3.0.5 on 2020-06-29 05:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfuaniweb', '0002_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='screenings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of blog posting', max_length=255)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('hotel_Main_Img', models.ImageField(upload_to='img/screens/')),
                ('datetime', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='gallery',
            name='tag',
            field=models.CharField(default=1, help_text='Topic of photo', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news_post',
            name='tag',
            field=models.CharField(default=1, help_text='Topic of photo', max_length=255),
            preserve_default=False,
        ),
    ]
