# Generated by Django 3.0.5 on 2020-08-27 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfuaniweb', '0003_auto_20200628_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_post',
            name='cover_image',
            field=models.ImageField(default='img/cover/logo.jpg', upload_to='img/cover/'),
        ),
    ]
