# Generated by Django 3.0.5 on 2020-08-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfuaniweb', '0004_news_post_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_post',
            name='author',
            field=models.CharField(default='SFU Exec Team', help_text='Author', max_length=255),
        ),
        migrations.AddField(
            model_name='news_post',
            name='pinned',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
