# Generated by Django 3.0.5 on 2020-08-31 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfuaniweb', '0007_event_countdown'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_countdown',
            old_name='event',
            new_name='title',
        ),
        migrations.AddField(
            model_name='event_countdown',
            name='cover_image',
            field=models.ImageField(default='img/cover/logo.jpg', upload_to='img/cover/'),
        ),
    ]
