# Generated by Django 3.0.5 on 2020-08-31 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfuaniweb', '0008_auto_20200830_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenings',
            name='colour_code',
            field=models.CharField(default='#f2c7f2', help_text='Colour Background', max_length=255),
        ),
    ]
