# Generated by Django 3.0.5 on 2020-08-31 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfuaniweb', '0009_screenings_colour_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_post',
            name='body_alt',
            field=models.CharField(help_text='Title of blog posting', max_length=255, null=True),
        ),
    ]
