# Generated by Django 3.0.5 on 2020-08-31 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfuaniweb', '0010_news_post_body_alt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_post',
            name='body_alt',
        ),
        migrations.AddField(
            model_name='index_cover',
            name='body_alt',
            field=models.CharField(help_text='Title of blog posting', max_length=255, null=True),
        ),
    ]
